# application-test.yml
server:
  port: 8081

spring:
  application:
    name: MyApp-Dev

  thymeleaf:
    cache: false # ??? ???? ?? -> ?? ? ?? ???
    prefix: classpath:/templates/ # ??? ?? ??
    suffix: .html # ??? ?? ???
    mode: HTML # HTML5 ??
    encoding: UTF-8 # ??? ??**